services:
  db-auth-api:
    image: postgres:18-alpine
    container_name: db-auth-api
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  auth-api:
    build: .
    container_name: auth-api
    ports: 
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - API_RATE_LIMIT_MAX=${API_RATE_LIMIT_MAX}
      - API_RATE_LIMIT_WINDOW=${API_RATE_LIMIT_WINDOW}
      - TOKEN_ACCESS=${TOKEN_ACCESS}
      - TOKEN_ACCESS_REFRESH=${TOKEN_ACCESS_REFRESH}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db-auth-api
volumes:
  postgres_data: